### ISSUE TITLE
Can all parameters of the callback be passed?

### ISSUE THREAD

**Issue by QuantBull** [shixiongfei/napi-ctp#2]
hi @shixiongfei , I have a suggestion for the library.
Let's use the following code as an example:
```c++
void MdSpi::OnRspSubMarketData(CThostFtdcSpecificInstrumentField *pSpecificInstrument, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast) {
  if (checkErrorRspInfo(pRspInfo, nRequestID, bIsLast))
    return;

  _msgq.push(EM_RSPSUBMARKETDATA, copyData(pSpecificInstrument));
}
```
The `nRequestID` and `bIsLast` are omitted, but they maybe useful in certain scenarios.

Such as: 
1. Some callbacks may be called multiple times consecutively with different values of `bIsLast`, perhaps the user only wants to do some logical processing when `bIsLast` is true.
2. If users want to develop a program that supports multiple trading accounts, `nRequestID` may be very useful (if users can set `nRequestID` themselves when calling some APIs).

If this library could encapsulate c++ interfaces one-on-one as javascript interfaces without adding any other processing logic, it would be even better, which would bring more flexibility and selectivity to developers.

**Comment by shixiongfei** [comment]
Actually, I wrote this library for myself. However, I think your suggestion is very good and I am glad that this library can also be helpful to you. 

The first suggestion I think I can make some modifications at an appropriate time.

The second suggestion needs to consider the compromise between ease of use and user customization, as I don't want to always set `nRequestID` in the logic.

At present, there is very little additional logic in this library, which is also intended to simplify the use.

**Comment by shixiongfei** [comment]
Hi @southwhale, now `isLast` has been passed as a parameter in the object to the callback function.

There may be more confusion and complexity between user specified `nRequestID` and automatic generation of `nRequestID`, as this is a transaction interface and we do not want to lose money due to program negligence.

Considering that JavaScript is a very flexible language, can multiple account requirements be implemented using closures or objects.

If there is no better reason, I may not support users specifying `nRequestID`.

**Comment by QuantBull** [comment]
I agree with your point on `nRequestID`. Thank you.
