### ISSUE TITLE
Error: throw "dyld[42087]: missing symbol called" in mac os.

### ISSUE THREAD

**Issue by QuantBull** [shixiongfei/napi-ctp#3]
as title described.
env: mb pro, Ventura 13.5.1.

**Comment by shixiongfei** [comment]
more info?

**Comment by QuantBull** [comment]
No more detailed information available. The terminal only returned one line of error message.
The error occurred when I updated `tradeapi` to version 6.7.0.

**Comment by shixiongfei** [comment]
Can you provide minimal reproducible code?

**Comment by QuantBull** [comment]
https://github.com/southwhale/napi-ctp-for-macos-issue

only update the libs of macos to version 6.7.0

**Comment by shixiongfei** [comment]
For what reason is it necessary to use version 6.7.0? The MacOS version 6.7.0 is a Framework. Is your .a file renamed from the Framework?

In addition, can you provide the minimized code that causes the problem when you use `napi-ctp`?

**Comment by QuantBull** [comment]
Acutally, I am not familar with the c++, I don't know how to reduce the unnecessary code(I am not sure which code are redundant for debug).
I just replaced the libs and built the project and ran `node test.js`, and then got the error. 
And the reason why I am using version 6.7.0 is just to make the CTP version as up-to-date as possible.
I think it is not a problem while I can use the project which consumes the CTP version 6.6.9.
Thanks for your reply.

**Comment by shixiongfei** [comment]
You don't need to reduce any `napi-ctp` debugging code. Providing minimized code means the minimum code that reproduces the problem you use `napi-ctp` to cause. So that I can see if it's a problem with the use or `napi-ctp` itself.

In fact, the compilation method of CTP `6.7.0` framework and other .a versions may be different, which is why `napi-ctp` is only upgraded to version `6.6.9`. I will consider upgrading to the latest version if necessary in the future.
